use_frameworks!

platform :ios, '8.0'

target 'FakeTencent_Example' do
  pod 'FakeTencent', :path => '../'

  target 'FakeTencent_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
